2023-03-13 23:52:49,235 INFO    MainThread:18412 [wandb_setup.py:_flush():68] Configure stats pid to 18412
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\.config\wandb\settings
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\settings
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_235249-ojjp645f\logs\debug.log
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_235249-ojjp645f\logs\debug-internal.log
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_init.py:init():532] calling init triggers
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_init.py:init():539] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'Homo-GNN', 'num_layers': 4, 'dataset': '1-HV-mixed--0-no_sw', 'epochs': 1000, 'activation': 'ReLu', 'dropout': 0.0, 'in_channels': 4, 'output_channels': 4, 'hidden_channels': 256, 'channel type': 'GraphConv', 'norm': 'BatchNorm'}
2023-03-13 23:52:49,236 INFO    MainThread:18412 [wandb_init.py:init():555] re-initializing run, found existing run on stack: cczt4fhh
2023-03-13 23:52:49,238 INFO    MainThread:18412 [wandb_run.py:_finish():1854] finishing run cbml/OPF-GNN-Supervised-Homo/cczt4fhh
2023-03-13 23:52:49,238 INFO    MainThread:18412 [jupyter.py:save_history():449] not saving jupyter history
2023-03-13 23:52:49,238 INFO    MainThread:18412 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-13 23:52:49,238 INFO    MainThread:18412 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-13 23:52:49,238 INFO    MainThread:18412 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-13 23:52:49,239 INFO    MainThread:18412 [wandb_run.py:_restore():2066] restore
2023-03-13 23:52:49,239 INFO    MainThread:18412 [wandb_run.py:_restore():2072] restore done
2023-03-13 23:53:06,363 INFO    MainThread:18412 [wandb_init.py:init():588] starting backend
2023-03-13 23:53:06,363 INFO    MainThread:18412 [wandb_init.py:init():592] setting up manager
2023-03-13 23:53:06,365 INFO    MainThread:18412 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2023-03-13 23:53:06,366 INFO    MainThread:18412 [wandb_init.py:init():599] backend started and connected
2023-03-13 23:53:06,374 INFO    MainThread:18412 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-13 23:53:06,374 INFO    MainThread:18412 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-13 23:53:06,374 INFO    MainThread:18412 [wandb_init.py:init():687] updated telemetry
2023-03-13 23:53:06,416 INFO    MainThread:18412 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-13 23:53:07,407 WARNING MsgRouterThr:18412 [router.py:message_loop():77] message_loop has been closed
2023-03-13 23:53:07,411 WARNING MsgRouterThr:18412 [router.py:message_loop():77] message_loop has been closed
2023-03-13 23:53:07,422 WARNING MainThread:18412 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_init.py", line 733, in init
    cancel=True,
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Users\canba\anaconda3\envs\code\lib\threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\canba\anaconda3\envs\code\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
